### ISSUE TITLE
Platform error weather.bom_forecast

### ISSUE THREAD

**Issue by oneseventhree** [DavidFW1960/bom_forecast#2]
Hi,

I have used HACS to install and when I add this to my config file:
```
# BOM Weather
  - platform: bom_forecast
    product_id: IDV10450
    name: Melbourne
    forecast_days: 6
    rest_of_today: true
    friendly: false
    friendly_state_format: '{max}, {summary}'
    monitored_conditions:
      - 'max'
      - 'min'
      - 'chance_of_rain'
      - 'possible_rainfall'
      - 'summary'
      - 'detailed_summary'
      - 'icon'
      - 'uv_alert'
      - 'fire_danger'
```

I get:
Platform error weather.bom_forecast - No module named 'custom_components.bom_forecast.weather'
<img width="609" alt="Screen Shot 2020-04-21 at 12 04 07 pm" src="https://user-images.githubusercontent.com/15043282/79817183-3db21400-83c8-11ea-888e-88b1225160af.png">

when I check my config

I have this in my custom components folder that HACS installed:
<img width="430" alt="Screen Shot 2020-04-21 at 12 05 32 pm" src="https://user-images.githubusercontent.com/15043282/79817289-78b44780-83c8-11ea-8496-4ef6ea474628.png">

How can I resolve this?

Thanks in advance

**Comment by DavidFW1960** [comment]
Hi there...
Did you try removing the configuration and restarting first then adding the config back and restarting/checking again? Lots of times when you add a custom component, the config check will fail until the component has been loaded and the component can't load unless you restart.

Also.. sorry I didn't see this issue until now. For some weird reason I don't get notifications for NEW issues... but I will get future notifications for this one now.

**Comment by troykelly** [comment]
I'm also seeing this error @DavidFW1960 - I've tried restarting HA with no config definition - but the error persists when I add the config back.

```
2020-06-22 01:54:24 ERROR (MainThread) [homeassistant.config] Platform error: weather
Traceback (most recent call last):
  File "/workspaces/new-belcastro/homeassistant/config.py", line 780, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/workspaces/new-belcastro/homeassistant/loader.py", line 321, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.bom_forecast.weather'
```

**Comment by oneseventhree** [comment]
> I'm also seeing this error @DavidFW1960 - I've tried restarting HA with no config definition - but the error persists when I add the config back.
> 
> ```
> 2020-06-22 01:54:24 ERROR (MainThread) [homeassistant.config] Platform error: weather
> Traceback (most recent call last):
>   File "/workspaces/new-belcastro/homeassistant/config.py", line 780, in async_process_component_config
>     platform = p_integration.get_platform(domain)
>   File "/workspaces/new-belcastro/homeassistant/loader.py", line 321, in get_platform
>     cache[full_name] = importlib.import_module(
>   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'custom_components.bom_forecast.weather'
> ```

Not sure if this helps but this is in my config.yaml:
```
# BOM Forecast ('sensor:' linked with BOM Weather)
#sensor:
  - platform: bom_forecast
    product_id: IDV10450 # http://www.bom.gov.au/products/IDV60801/IDV60801.95936.shtml
    name: Melbourne
    forecast_days: 6
    rest_of_today: true
    friendly: false
    friendly_state_format: '{max}, {summary}'
    monitored_conditions:
      - 'max'
      - 'min'
      - 'chance_of_rain'
      - 'possible_rainfall'
      - 'summary'
      - 'icon'
```

Also make sure bom_forecast folder is in your custom_components.

Can't remember what I did to fix it sorry!
