### ISSUE TITLE
All except today's min temp are available

### ISSUE THREAD

**Issue by sabellwind** [DavidFW1960/bom_forecast#7]
Hi there, thanks for building this custom integration. I've installed via HACS and used the weather.yaml package pre-0.115.x. Using Melbourne as my location, I did a find and replace on 'gosford' for 'melbourne' and these are my bom station/product/name configs:
```
my_bom_station: 
my_bom_name: Melbourne
my_bom_product_id: IDV10450
```
My problem is that I'm getting all forecasts come through except for the min temp of today:
![image](https://user-images.githubusercontent.com/57622159/94324279-7dff6900-ffdc-11ea-8609-f9d9b5667553.png)

![image](https://user-images.githubusercontent.com/57622159/94324304-9b343780-ffdc-11ea-88cf-4f899a10bcbf.png)

I've tried forcing an update via the homeassistant.updateentity restarting home assistant. Logs don't show anything sinister in particular.

Here are all my min_0 blocks of yaml:
```
      bom_forecast_0:
        entity_id:
          - sensor.bom_today_max
          - sensor.bom_today_min
          - sensor.bom_melbourne_chance_of_rain_0
          - sensor.bom_melbourne_icon_0
        friendly_name: "Today"
        value_template: >
          {{states('sensor.bom_today_max')|round(0)}}°/{{states('sensor.bom_today_min')|round(0)}}°/{{states('sensor.bom_melbourne_chance_of_rain_0')|round(0)}}%
        entity_picture_template: >-
          {%- if states('sun.sun') == 'below_horizon' and (states('sensor.bom_melbourne_icon_0') == 'fog' or states('sensor.bom_melbourne_icon_0') == 'haze' or states('sensor.bom_melbourne_icon_0') == 'light-showers' or states('sensor.bom_melbourne_icon_0') == 'partly-cloudy' or states('sensor.bom_melbourne_icon_0') == 'showers') -%}
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_melbourne_icon_0') ~ '-night.png' }}
          {%- else -%}
          {{ '/local/icons/bom_icons/' ~ states('sensor.bom_melbourne_icon_0') ~ '.png' }}
          {%- endif -%}
```
```
      bom_today_min:
        entity_id:
          - sensor.bom_melbourne_min_temp_c_0
          - sensor.today_temp_bom
        value_template: >
          {%- if states('sensor.bom_melbourne_min_temp_c_0') == 'n/a' -%} 
            {{ state_attr('sensor.today_temp_bom', 'min_value') }}
          {% else %}
            {{ states('sensor.bom_melbourne_min_temp_c_0') }}
          {% endif %}
```

Any ideas on how to get this one working?

**Comment by DavidFW1960** [comment]
Yeah. You are missing a statistics sensor which creates sensor.today_temp_bom. It's shown in the package.
```
  - platform: statistics
    name: today_temp_bom
    sampling_size: 150
    entity_id: sensor.bom_melbourne_air_temp_c
    max_age:
      hours: 24
```
You will see errors in your log as well.
BOM shows the min (and max) temps as n/a after the min/max for the day is reached (around 4am for min and 3pm for max) so that stats sensor will give the other templates the min/max for the last 24 hours. I use the custom_component average instead as it will give me max/min since midnight which I think is better and more accurate. You can see that if you look in my personal home assistant repo.

**Comment by sabellwind** [comment]
Hi mate. I just checked, and that's already there. Just wasn't sure if it was necessary to share:
![image](https://user-images.githubusercontent.com/57622159/94325809-a0e14b80-ffe3-11ea-971b-67c165372401.png)

Here's the sensor:
![image](https://user-images.githubusercontent.com/57622159/94326023-cfabf180-ffe4-11ea-8833-2883b0c1b28a.png)

I'd like to see if I can get this working before I move to yet another custom component for average.

**Comment by sabellwind** [comment]
Seeing as this takes previous values to derive the current value, it would take at least 24 hours to get this value? I only got this flowing at around 5pm last night.

**Comment by DavidFW1960** [comment]
yes... but you will need the custom component average as well. (I agree. get stats working first)
Do you have a sensor.today_temp_bom
![image](https://user-images.githubusercontent.com/36390762/94325963-88256580-ffe4-11ea-9949-362f25a234f0.png)

Also what do you see for sensor.bom_melbourne_air_temp_c
![image](https://user-images.githubusercontent.com/36390762/94326086-3c26f080-ffe5-11ea-9b19-9df96fe5222e.png)

It seems like stats is not getting any data to calc min/max (For YOU I mean... mine is ok)

> Seeing as this takes previous values to derive the current value, it would take at least 24 hours to get this value? I only got this flowing at around 5pm last night.

It only takes one reading from BOM for the min/max to start working. Not 24 hrs..

**Comment by sabellwind** [comment]
sensor.today_temp_bom:
![image](https://user-images.githubusercontent.com/57622159/94326269-40074280-ffe6-11ea-99d9-c18168a0e748.png)

I don't have a sensor.bom_melbourne_air_temp_c come up. I think this is where the issue is.
![image](https://user-images.githubusercontent.com/57622159/94326351-b146f580-ffe6-11ea-87e6-89eed5e9e7e3.png)

**Comment by DavidFW1960** [comment]
yeah you don't have the Core BOM component working. Looks like you do have the FTP Forecast just not the core BOM one.
Here is my config:
```
sensor:
  - platform: bom
    station: !secret my_bom_station
    name: !secret my_bom_name
    monitored_conditions:
      - apparent_t
      - delta_t
      - gust_kmh
      - gust_kt
      - air_temp
      - dewpt
      - rain_trace
      - rel_hum
      - wind_dir
      - wind_spd_kmh
      - wind_spd_kt

  - platform: bom_forecast
    product_id: !secret my_bom_product_id
    name: !secret my_bom_name
    forecast_days: 6
    rest_of_today: true
    friendly: false
    friendly_state_format: '{max}, {summary}'
    monitored_conditions:
      - 'max'
      - 'min'
      - 'chance_of_rain'
      - 'possible_rainfall'
      - 'summary'
      - 'detailed_summary'
      - 'icon'
      - 'uv_alert'
      - 'fire_danger'
```
