### ISSUE TITLE
Tutorial - Help on how to configure Bom_Forecast - hope it helps others

### ISSUE THREAD

**Issue by exup** [DavidFW1960/bom_forecast#8]
Hi, trying to get the weather to show the forecast as per your guide. But when I add the card it only shows current temp. I think I am getting confused some where. 
In HACS I have the BOM weather card, but in the dashboard when I go to add it I can only see the standard forecast card and custom weather card.
In Dashboard I select the custom weather card and in the drop down entity weather.bom_terrey_hills  but it just shows current temp and all the other variables.

I have the folder /config/custom_components/bom_forecast installed via HAC and has the relevant files installed.
This is my configuration.yaml file.

weather:
  - platform: bom
    station: IDN60901.94759

sensor:
  - platform: bom
    station: IDN60901.94759
    monitored_conditions:
      - apparent_t
      - cloud
      - cloud_base_m
      - cloud_oktas
      - cloud_type_id
      - cloud_type
      - delta_t
      - gust_kmh
      - gust_kt
      - air_temp
      - dewpt
      - local_date_time
      - local_date_time_full
      - press
      - press_qnh
      - press_msl
      - press_tend
      - rain_trace
      - rel_hum
      - sea_state
      - swell_dir_worded
      - swell_height
      - swell_period
      - vis_km
      - weather
      - wind_dir
      - wind_spd_kmh
      - wind_spd_kt
  - platform: bom_forecast
    #product_id: IDN11060
    name: Terrey Hills         #In my examples I use Gosford
    forecast_days: 6
    rest_of_today: true
    friendly: false
    friendly_state_format: '{max}, {summary}'
    monitored_conditions:
      - 'max'
      - 'min'
      - 'chance_of_rain'
      - 'possible_rainfall'
      - 'summary'
      - 'detailed_summary'
      - 'icon'
      - 'uv_alert'
      - 'fire_danger'

**Comment by DavidFW1960** [comment]
It.  Isn't using the inbuilt 'weather' platform. All mine use sensors.
The weather card example I show here is using TEMPLATE sensors so you need those. Then you can display them on an entity card.
My BOM weather card needs to be added as a manual card... not built into lovelace.

**Comment by exup** [comment]
OK I am a bit new to Home assistant, could you point me in the direction to setting up a manual card, I can see the entry is minimal 
Any chance you could paste a sample card config 

This is what I did, create a manual card and pasted this in, but its still blank, I did confirm all the entities exist and have values. Maybe my formatting is wrong, but it did accept the values. (as in no errors)

  type: custom:bom-weather-card
  title: BOM Weather
  entity_current_conditions: sensor.bom_terrey_hills_icon_0
  entity_temperature: sensor.bom_terrey_hills_air_temp_c
  entity_forecast_high_temp_1: sensor.bom_terrey_hills_max_temp_c_1
  entity_forecast_high_temp_2: sensor.bom_terrey_hills_max_temp_c_2
  entity_forecast_high_temp_3: sensor.bom_terrey_hills_max_temp_c_3
  entity_forecast_high_temp_4: sensor.bom_terrey_hills_max_temp_c_4
  entity_forecast_high_temp_5: sensor.bom_terrey_hills_max_temp_c_5
  entity_forecast_icon_1: sensor.bom_terrey_hills_icon_1
  entity_forecast_icon_2: sensor.bom_terrey_hills_icon_2
  entity_forecast_icon_3: sensor.bom_terrey_hills_icon_3
  entity_forecast_icon_4: sensor.bom_terrey_hills_icon_4
  entity_forecast_icon_5: sensor.bom_terrey_hills_icon_5
  entity_forecast_low_temp_1: sensor.bom_terrey_hills_min_temp_c_1
  entity_forecast_low_temp_2: sensor.bom_terrey_hills_min_temp_c_2
  entity_forecast_low_temp_3: sensor.bom_terrey_hills_min_temp_c_3
  entity_forecast_low_temp_4: sensor.bom_terrey_hills_min_temp_c_4
  entity_forecast_low_temp_5: sensor.bom_terrey_hills_min_temp_c_5
  entity_summary_1: sensor.bom_terrey_hills_summary_1
  entity_summary_2: sensor.bom_terrey_hills_summary_2
  entity_summary_3: sensor.bom_terrey_hills_summary_3
  entity_summary_4: sensor.bom_terrey_hills_summary_4
  entity_summary_5: sensor.bom_terrey_hills_summary_5

**Comment by DavidFW1960** [comment]
did you check in dev-tools that all of those sensors actually exist? (eg sensor.bom_terrey_hills_icon_0)
I have provided examples it the card repo. You can also see my own configuration here:
https://github.com/DavidFW1960/home-assistant
In Home assistant, click 3 dot menu in top right corner, select edit dashboard then + in bottom right. Scroll down and click manual card.
![image](https://user-images.githubusercontent.com/36390762/95691800-9ecaee00-0c6d-11eb-9415-efefde80102e.png)
Then past the above code. As long as those sensors exist you should see the card.

**Comment by exup** [comment]
Hi yes I check in DevTools and can see that each one is getting a value see screen shot of Max temps, and that is what I have copied into the card as you described but still its blank. I have created a new dashboard with just this card on and pasted the Raw configuration. Am I missing anything? For example the resources url cannot be added any more to the RAW config.

![image](https://user-images.githubusercontent.com/61529003/95693023-c6be4f80-0c75-11eb-8c38-bf6a5dc8253b.png)
![image](https://user-images.githubusercontent.com/61529003/95693182-c3779380-0c76-11eb-9b44-fe8b59126aeb.png)
![image](https://user-images.githubusercontent.com/61529003/95693198-d25e4600-0c76-11eb-8876-86d465347b66.png)
The dashboard is just blank?

**Comment by DavidFW1960** [comment]
Does the sensor.bom_terrey_hills_air_temp_c exist? That one is created by the Core BOM integration...
The resources for the card are added in the GUI... /config/lovelace/resources
Otherwise post your sensor configuration for the ftp and core component and I'll run it up in a VM...
Make sure you use code blocks... either the <> icon in the toolbar of the message or three backticks on previous line and last line. (Back ticks are to the left of the 1 key on keyboard and are not the same character as single quotes)

**Comment by exup** [comment]
Hi subtle difference it has custom in the entity?
But I noted your comment about ' versus ` so will edit it again with the proper back tick.
![image](https://user-images.githubusercontent.com/61529003/95693698-6204f400-0c79-11eb-94b0-a9b84e68796b.png)

**Comment by exup** [comment]
Ah sorry I see what you mean about back ticks not in my code but posting code here "doh!"
```
sensor:
  - platform: bom
    station: IDN60901.94759
    monitored_conditions:
      - apparent_t
      - cloud
      - cloud_base_m
      - cloud_oktas
      - cloud_type_id
      - cloud_type
      - delta_t
      - gust_kmh
      - gust_kt
      - air_temp
      - dewpt
      - local_date_time
      - local_date_time_full
      - press
      - press_qnh
      - press_msl
      - press_tend
      - rain_trace
      - rel_hum
      - sea_state
      - swell_dir_worded
      - swell_height
      - swell_period
      - vis_km
      - weather
      - wind_dir
      - wind_spd_kmh
      - wind_spd_kt
  - platform: bom_forecast
    #product_id: IDN11060
    name: Terrey Hills         #In my examples I use Gosford
    forecast_days: 6
    rest_of_today: true
    friendly: false
    friendly_state_format: '{max}, {summary}'
    monitored_conditions:
      - 'max'
      - 'min'
      - 'chance_of_rain'
      - 'possible_rainfall'
      - 'summary'
      - 'detailed_summary'
      - 'icon'
      - 'uv_alert'
      - 'fire_danger'

    
weather:
  - platform: bom
    station: IDN60901.94759
```
